/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Algoritmo;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class jFInterfazDijkstra extends javax.swing.JFrame {

    /**
     * Creates new form jFInterfazDijkstra
     */
    Graph grafo;
    int origen;
    int destino;
    int peso;
    String info;
    String vertices;
    String djikstra;
    
    public jFInterfazDijkstra() {
        initComponents();
        this.jP4Vertices.setVisible(false);
        this.jP5Vertices.setVisible(false);
        this.jP6Vertices.setVisible(false);
        this.jPResultados.setVisible(false);
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCBNúmeroNodos = new javax.swing.JComboBox<>();
        jP4Vertices = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCBOrigenDe4 = new javax.swing.JComboBox<>();
        jCBDestinoDe4 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTFPesoDe4 = new javax.swing.JTextField();
        JBAgregarDe4 = new javax.swing.JButton();
        jBNuevo4 = new javax.swing.JButton();
        jP5Vertices = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCBOrigenDe5 = new javax.swing.JComboBox<>();
        jCBDestinoDe5 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTFPesoDe5 = new javax.swing.JTextField();
        jBAgregarDe5 = new javax.swing.JButton();
        jBNuevo5 = new javax.swing.JButton();
        jP6Vertices = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jCBOrigenDe6 = new javax.swing.JComboBox<>();
        jCBDestinoDe6 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jTFPesoDe6 = new javax.swing.JTextField();
        jBAgregarDe6 = new javax.swing.JButton();
        jBNuevo6 = new javax.swing.JButton();
        jPResultados = new javax.swing.JPanel();
        jBAplicarDijsktra = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAInfoGrafo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAResultadosDjikstra = new javax.swing.JTextArea();
        jBNuevoTodo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Ebrima", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("APLICACIÓN DIJKSTRA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(210, 210, 210))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(40, 40, 40))
        );

        jLabel2.setText("Número de Nodos:");

        jCBNúmeroNodos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Opciones--", "4", "5", "6" }));
        jCBNúmeroNodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBNúmeroNodosActionPerformed(evt);
            }
        });

        jP4Vertices.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Aristas"));

        jLabel3.setText("Nodo Origen:");

        jLabel4.setText("Nodo Destino:");

        jCBOrigenDe4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--ARISTAS--", "A", "B", "C", "D" }));
        jCBOrigenDe4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBOrigenDe4ActionPerformed(evt);
            }
        });

        jCBDestinoDe4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--ARISTAS--", "A", "B", "C", "D" }));
        jCBDestinoDe4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBDestinoDe4ActionPerformed(evt);
            }
        });

        jLabel5.setText("Peso:");

        JBAgregarDe4.setText("AÑADIR ARISTA");
        JBAgregarDe4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAgregarDe4ActionPerformed(evt);
            }
        });

        jBNuevo4.setText("NUEVO");
        jBNuevo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevo4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP4VerticesLayout = new javax.swing.GroupLayout(jP4Vertices);
        jP4Vertices.setLayout(jP4VerticesLayout);
        jP4VerticesLayout.setHorizontalGroup(
            jP4VerticesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP4VerticesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP4VerticesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP4VerticesLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jCBOrigenDe4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP4VerticesLayout.createSequentialGroup()
                        .addGroup(jP4VerticesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jP4VerticesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP4VerticesLayout.createSequentialGroup()
                                .addComponent(jCBDestinoDe4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTFPesoDe4))))
                .addContainerGap())
            .addGroup(jP4VerticesLayout.createSequentialGroup()
                .addComponent(JBAgregarDe4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBNuevo4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jP4VerticesLayout.setVerticalGroup(
            jP4VerticesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP4VerticesLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jP4VerticesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jCBOrigenDe4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP4VerticesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCBDestinoDe4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP4VerticesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFPesoDe4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jP4VerticesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBAgregarDe4)
                    .addComponent(jBNuevo4))
                .addContainerGap())
        );

        jP5Vertices.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Aristas"));

        jLabel6.setText("Nodo Origen:");

        jLabel7.setText("Nodo Destino:");

        jCBOrigenDe5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--ARISTAS--", "A", "B", "C", "D", "E" }));
        jCBOrigenDe5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBOrigenDe5ActionPerformed(evt);
            }
        });

        jCBDestinoDe5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--ARISTAS--", "A", "B", "C", "D", "E" }));
        jCBDestinoDe5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBDestinoDe5ActionPerformed(evt);
            }
        });

        jLabel8.setText("Peso:");

        jBAgregarDe5.setText("AÑADIR ARISTA");
        jBAgregarDe5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarDe5ActionPerformed(evt);
            }
        });

        jBNuevo5.setText("NUEVO");
        jBNuevo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevo5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP5VerticesLayout = new javax.swing.GroupLayout(jP5Vertices);
        jP5Vertices.setLayout(jP5VerticesLayout);
        jP5VerticesLayout.setHorizontalGroup(
            jP5VerticesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP5VerticesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP5VerticesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP5VerticesLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jCBOrigenDe5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP5VerticesLayout.createSequentialGroup()
                        .addGroup(jP5VerticesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jP5VerticesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCBDestinoDe5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTFPesoDe5)))
                    .addGroup(jP5VerticesLayout.createSequentialGroup()
                        .addComponent(jBAgregarDe5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBNuevo5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP5VerticesLayout.setVerticalGroup(
            jP5VerticesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP5VerticesLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jP5VerticesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jCBOrigenDe5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP5VerticesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jCBDestinoDe5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP5VerticesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTFPesoDe5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jP5VerticesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAgregarDe5)
                    .addComponent(jBNuevo5))
                .addContainerGap())
        );

        jP6Vertices.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Aristas"));

        jLabel9.setText("Nodo Origen:");

        jLabel10.setText("Nodo Destino:");

        jCBOrigenDe6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--ARISTAS--", "A", "B", "C", "D", "E", "F" }));
        jCBOrigenDe6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBOrigenDe6ActionPerformed(evt);
            }
        });

        jCBDestinoDe6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--ARISTAS--", "A", "B", "C", "D", "E", "F" }));
        jCBDestinoDe6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBDestinoDe6ActionPerformed(evt);
            }
        });

        jLabel11.setText("Peso:");

        jBAgregarDe6.setText("AÑADIR ARISTA");
        jBAgregarDe6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarDe6ActionPerformed(evt);
            }
        });

        jBNuevo6.setText("NUEVO");
        jBNuevo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevo6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP6VerticesLayout = new javax.swing.GroupLayout(jP6Vertices);
        jP6Vertices.setLayout(jP6VerticesLayout);
        jP6VerticesLayout.setHorizontalGroup(
            jP6VerticesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP6VerticesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP6VerticesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP6VerticesLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jCBOrigenDe6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP6VerticesLayout.createSequentialGroup()
                        .addGroup(jP6VerticesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jP6VerticesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCBDestinoDe6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTFPesoDe6)))
                    .addGroup(jP6VerticesLayout.createSequentialGroup()
                        .addComponent(jBAgregarDe6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBNuevo6)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jP6VerticesLayout.setVerticalGroup(
            jP6VerticesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP6VerticesLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jP6VerticesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jCBOrigenDe6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP6VerticesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jCBDestinoDe6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP6VerticesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTFPesoDe6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jP6VerticesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAgregarDe6)
                    .addComponent(jBNuevo6))
                .addContainerGap())
        );

        jBAplicarDijsktra.setText("APLICAR DIJKSTRA");
        jBAplicarDijsktra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAplicarDijsktraActionPerformed(evt);
            }
        });

        jTAInfoGrafo.setColumns(20);
        jTAInfoGrafo.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jTAInfoGrafo.setRows(5);
        jTAInfoGrafo.setBorder(javax.swing.BorderFactory.createTitledBorder("Información del Grafo"));
        jScrollPane1.setViewportView(jTAInfoGrafo);

        jTAResultadosDjikstra.setColumns(20);
        jTAResultadosDjikstra.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jTAResultadosDjikstra.setRows(5);
        jTAResultadosDjikstra.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados Dijkstra"));
        jScrollPane2.setViewportView(jTAResultadosDjikstra);

        jBNuevoTodo.setText("NUEVO");
        jBNuevoTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPResultadosLayout = new javax.swing.GroupLayout(jPResultados);
        jPResultados.setLayout(jPResultadosLayout);
        jPResultadosLayout.setHorizontalGroup(
            jPResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPResultadosLayout.createSequentialGroup()
                        .addComponent(jBAplicarDijsktra)
                        .addGap(18, 18, 18)
                        .addComponent(jBNuevoTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPResultadosLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPResultadosLayout.setVerticalGroup(
            jPResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBAplicarDijsktra, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jBNuevoTodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jP4Vertices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jP5Vertices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jP6Vertices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jCBNúmeroNodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jCBNúmeroNodos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jP4Vertices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jP5Vertices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jP6Vertices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBOrigenDe4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBOrigenDe4ActionPerformed
        int opc = this.jCBOrigenDe4.getSelectedIndex();
        
        switch(opc)
        {
            case 0:
                //JOptionPane.showMessageDialog(null, "ESCOJA UNA OPCIÓN");
                
            case 1:
                origen = 0;
                break;
            case 2:
                origen = 1;
                break;
            case 3:
                origen = 2;
                break;
            case 4:
                origen = 3;
                break;
        }
    }//GEN-LAST:event_jCBOrigenDe4ActionPerformed

    private void jCBNúmeroNodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBNúmeroNodosActionPerformed
        int opc = this.jCBNúmeroNodos.getSelectedIndex();
        
        switch(opc)
        {
            case 0:
                //JOptionPane.showMessageDialog(null, "ESCOJA UNA OPCIÓN");

                
            case 1:
                grafo = new Graph(4);
                this.jP4Vertices.setVisible(true);
                this.jP5Vertices.setVisible(false);
                this.jP6Vertices.setVisible(false);
                this.jPResultados.setVisible(true);
                
                grafo.addVertax("A");//0
                grafo.addVertax("B");//1
                grafo.addVertax("C");//2
                grafo.addVertax("D");//3
                
                info = ("Vértices del Grafo: A  B  C  D  " );
                this.jTAInfoGrafo.setText(info);
                break;
            
            case 2:
                grafo = new Graph(5);
                this.jP4Vertices.setVisible(false);
                this.jP5Vertices.setVisible(true);
                this.jP6Vertices.setVisible(false);
                this.jPResultados.setVisible(true);
                
                grafo.addVertax("A");//0
                grafo.addVertax("B");//1
                grafo.addVertax("C");//2
                grafo.addVertax("D");//3
                grafo.addVertax("E");//4
                
                info = ("Vértices del Grafo: A  B  C  D  E " );
                this.jTAInfoGrafo.setText(info);
                
                break;
                
            case 3:
                grafo = new Graph(6);
                this.jP4Vertices.setVisible(false);
                this.jP5Vertices.setVisible(false);
                this.jP6Vertices.setVisible(true);
                this.jPResultados.setVisible(true);
                
                grafo.addVertax("A");//0
                grafo.addVertax("B");//1
                grafo.addVertax("C");//2
                grafo.addVertax("D");//3
                grafo.addVertax("E");//4
                grafo.addVertax("F");//5
                
                info = ("Vértices del Grafo: A  B  C  D  E  F " );
                this.jTAInfoGrafo.setText(info);
                
                break;
        }
    }//GEN-LAST:event_jCBNúmeroNodosActionPerformed

    private void jCBDestinoDe4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBDestinoDe4ActionPerformed
        int opc = this.jCBDestinoDe4.getSelectedIndex();
        
        switch(opc)
        {
            case 0:
                //JOptionPane.showMessageDialog(null, "ESCOJA UNA OPCIÓN");
                
            case 1:
                destino = 0;
                break;
            case 2:
                destino = 1;
                break;
            case 3:
                destino = 2;
                break;
            case 4:
                destino = 3;
                break;
        }
    }//GEN-LAST:event_jCBDestinoDe4ActionPerformed

    private void JBAgregarDe4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAgregarDe4ActionPerformed

        if(this.jCBOrigenDe4.getSelectedIndex() == 0 || this.jCBDestinoDe4.getSelectedIndex() == 0)
        {
            JOptionPane.showMessageDialog(null, "ORIGEN O DESTINO NO ESPECIFICADO");
        } else
        
        {
            if(this.jTFPesoDe4.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "PESO NO ESPECIFICADO");
            } else{
                peso = Integer.parseInt(this.jTFPesoDe4.getText());
                grafo.addEdges(origen, destino, peso);
                String matriz = grafo.showEdges();
                vertices = "\nMatriz de Adyacencia" + "\n" + matriz;
                this.jTAInfoGrafo.setText(info + vertices);
            }
            
        }
        
    }//GEN-LAST:event_JBAgregarDe4ActionPerformed

    private void jBNuevo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevo4ActionPerformed
        this.jTFPesoDe4.setText("");
        this.jCBDestinoDe4.setSelectedIndex(0);
        this.jCBOrigenDe4.setSelectedIndex(0);
    }//GEN-LAST:event_jBNuevo4ActionPerformed

    private void jCBOrigenDe5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBOrigenDe5ActionPerformed
        int opc = this.jCBOrigenDe5.getSelectedIndex();
        
        switch(opc)
        {
            case 0:
                //JOptionPane.showMessageDialog(null, "ESCOJA UNA OPCIÓN");
                
            case 1:
                origen = 0;
                break;
            case 2:
                origen = 1;
                break;
            case 3:
                origen = 2;
                break;
            case 4:
                origen = 3;
                break;
            case 5:
                origen = 4;
                break;
        }
    }//GEN-LAST:event_jCBOrigenDe5ActionPerformed

    private void jCBDestinoDe5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBDestinoDe5ActionPerformed
        int opc = this.jCBDestinoDe5.getSelectedIndex();
        
        switch(opc)
        {
            case 0:
                //JOptionPane.showMessageDialog(null, "ESCOJA UNA OPCIÓN");
                
            case 1:
                destino = 0;
                break;
            case 2:
                destino = 1;
                break;
            case 3:
                destino = 2;
                break;
            case 4:
                destino = 3;
                break;
            case 5:
                destino = 4;
                break;
        }
    }//GEN-LAST:event_jCBDestinoDe5ActionPerformed

    private void jBAgregarDe5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarDe5ActionPerformed
        if(this.jCBOrigenDe5.getSelectedIndex() == 0 || this.jCBDestinoDe5.getSelectedIndex() == 0)
        {
            JOptionPane.showMessageDialog(null, "ORIGEN O DESTINO NO ESPECIFICADO");
        } else
        
        {
            if(this.jTFPesoDe5.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "PESO NO ESPECIFICADO");
            } else{
                peso = Integer.parseInt(this.jTFPesoDe5.getText());
                grafo.addEdges(origen, destino, peso);
                String matriz = grafo.showEdges();
                vertices = "\nMatriz de Adyacencia" + "\n" + matriz;
                this.jTAInfoGrafo.setText(info + vertices);
            }
            
        }
    }//GEN-LAST:event_jBAgregarDe5ActionPerformed

    private void jBNuevo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevo5ActionPerformed
        this.jTFPesoDe5.setText("");
        this.jCBDestinoDe5.setSelectedIndex(0);
        this.jCBOrigenDe5.setSelectedIndex(0);
    }//GEN-LAST:event_jBNuevo5ActionPerformed

    private void jCBOrigenDe6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBOrigenDe6ActionPerformed
        int opc = this.jCBOrigenDe6.getSelectedIndex();
        
        switch(opc)
        {
            case 0:
                //JOptionPane.showMessageDialog(null, "ESCOJA UNA OPCIÓN");
                
            case 1:
                origen = 0;
                break;
            case 2:
                origen = 1;
                break;
            case 3:
                origen = 2;
                break;
            case 4:
                origen = 3;
                break;
            case 5:
                origen = 4;
                break;
            case 6:
                origen = 5;
                break;
        }
    }//GEN-LAST:event_jCBOrigenDe6ActionPerformed

    private void jCBDestinoDe6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBDestinoDe6ActionPerformed
        int opc = this.jCBDestinoDe6.getSelectedIndex();
        
        switch(opc)
        {
            case 0:
                //JOptionPane.showMessageDialog(null, "ESCOJA UNA OPCIÓN");
                
            case 1:
                destino = 0;
                break;
            case 2:
                destino = 1;
                break;
            case 3:
                destino = 2;
                break;
            case 4:
                destino = 3;
                break;
            case 5:
                destino = 4;
                break;
            case 6:
                destino = 5;
                break;
        }
    }//GEN-LAST:event_jCBDestinoDe6ActionPerformed

    private void jBAgregarDe6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarDe6ActionPerformed
        if(this.jCBOrigenDe6.getSelectedIndex() == 0 || this.jCBDestinoDe6.getSelectedIndex() == 0)
        {
            JOptionPane.showMessageDialog(null, "ORIGEN O DESTINO NO ESPECIFICADO");
        } else
        
        {
            if(this.jTFPesoDe6.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "PESO NO ESPECIFICADO");
            } else{
                peso = Integer.parseInt(this.jTFPesoDe6.getText());
                grafo.addEdges(origen, destino, peso);
                String matriz = grafo.showEdges();
                vertices = "\nMatriz de Adyacencia" + "\n" + matriz;
                this.jTAInfoGrafo.setText(info + vertices);
            }
            
        }
    }//GEN-LAST:event_jBAgregarDe6ActionPerformed

    private void jBNuevo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevo6ActionPerformed
    
        this.jTFPesoDe6.setText("");
        this.jCBDestinoDe6.setSelectedIndex(0);
        this.jCBOrigenDe6.setSelectedIndex(0);
    }//GEN-LAST:event_jBNuevo6ActionPerformed

    private void jBAplicarDijsktraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAplicarDijsktraActionPerformed
        djikstra = grafo.dijkStra(0);
        this.jTAResultadosDjikstra.setText(djikstra);
    }//GEN-LAST:event_jBAplicarDijsktraActionPerformed

    private void jBNuevoTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoTodoActionPerformed
        this.jTAInfoGrafo.setText("");
        this.jTAResultadosDjikstra.setText("");
        this.jP4Vertices.setVisible(false);
        this.jP5Vertices.setVisible(false);
        this.jP6Vertices.setVisible(false);
        this.jPResultados.setVisible(false);
        
        jBNuevo4ActionPerformed(evt);
        jBNuevo5ActionPerformed(evt);
        jBNuevo6ActionPerformed(evt);
        
    }//GEN-LAST:event_jBNuevoTodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFInterfazDijkstra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFInterfazDijkstra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFInterfazDijkstra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFInterfazDijkstra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFInterfazDijkstra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAgregarDe4;
    private javax.swing.JButton jBAgregarDe5;
    private javax.swing.JButton jBAgregarDe6;
    private javax.swing.JButton jBAplicarDijsktra;
    private javax.swing.JButton jBNuevo4;
    private javax.swing.JButton jBNuevo5;
    private javax.swing.JButton jBNuevo6;
    private javax.swing.JButton jBNuevoTodo;
    private javax.swing.JComboBox<String> jCBDestinoDe4;
    private javax.swing.JComboBox<String> jCBDestinoDe5;
    private javax.swing.JComboBox<String> jCBDestinoDe6;
    private javax.swing.JComboBox<String> jCBNúmeroNodos;
    private javax.swing.JComboBox<String> jCBOrigenDe4;
    private javax.swing.JComboBox<String> jCBOrigenDe5;
    private javax.swing.JComboBox<String> jCBOrigenDe6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jP4Vertices;
    private javax.swing.JPanel jP5Vertices;
    private javax.swing.JPanel jP6Vertices;
    private javax.swing.JPanel jPResultados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTAInfoGrafo;
    private javax.swing.JTextArea jTAResultadosDjikstra;
    private javax.swing.JTextField jTFPesoDe4;
    private javax.swing.JTextField jTFPesoDe5;
    private javax.swing.JTextField jTFPesoDe6;
    // End of variables declaration//GEN-END:variables
}
